CREATE TABLE hechizo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(255),
    descripcion VARCHAR(255),
    tipo        VARCHAR(255),
    autorizado  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_hechizo PRIMARY KEY (id)
);